name: Run Config Parser

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # هر ۶ ساعت یک‌بار

jobs:
  parse-configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run PHP Script
        run: php core.php

      - name: Commit Updated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sub/*
          git commit -m "🔄 Update config files"
          git push
        continue-on-error: true
